name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos7, centos8, ubuntu18.04, ubuntu20.04, ubuntu20.10]
    container:
      image: electronioncollider/spack-builder:${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-spack@main
      with:
        environment: eic
    - name: Run CI scripts
      run: |
        source ${SPACK_ROOT}/share/spack/setup-env.sh
        if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
