name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: actions/cache@v2
      with:
        path: /var/lib/cvmfs
        key: ${{ runner.os }}-cvmfs

    - name: Setup spack
      env:
          SPACK_ROOT: /cvmfs/eic.opensciencegrid.org/packages/spack/current
      run: |
        # Setup spack
        echo "SPACK_ROOT=$SPACK_ROOT" >> $GITHUB_ENV
        echo "$SPACK_ROOT/bin" >> $GITHUB_PATH

    - name: Run CI scripts
      run: |
        source $SPACK_ROOT/share/spack/setup-env.sh
        if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
