name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [centos7, centos8, ubuntu18.04, ubuntu20.04, ubuntu20.10]
    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-singularity@v5
      with:
        singularity-version: 3.6.4
    - name: Run CI scripts
      run: |
        singularity run -B /cvmfs:/cvmfs /cvmfs/eic.opensciencegrid.org/singularity/spack-builder:${{matrix.os}} ls
        #if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
