name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # nightly at 1 AM
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-spack@main
      with:
        environment: eic
    - uses: actions/cache@v2
      with:
        path: /var/lib/cvmfs
        key: ${{ runner.os }}-cvmfs
    - name: Run CI scripts
      run: |
        if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
